apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: psac5-postgre
spec:
  interval: 5m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "16.0.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      postgresPassword: d5A6RXA%fu78PuPelwZ*
      username: user
      password: #t4PJKDw$$&ZHYi8&e53
      database: test-database

